reference: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/inputs/reference.fasta"
output_dir: "results_test_new" # no / at the end here allowed!! do path/to/dir instead of path/to/dir/
demultiplex: False  # Set to true to enable demultiplexing
use_kraken2: True # to check if all samples are truly human, finds contamination
use_cpg_tools: True # only makes sense if methylation data is in input. additional kinetics not needed
use_mitosaw: True # Mitochondrial variations, only hg38 supported
use_sv_annotation: False # only hg38 for now, needs database file and annotsv data installed.
use_snp_annotation: True 
use_deepvariant: True #  False uses bcftools. deepvariant is much better and should be prefered
use_deepvariant_hpc: True
# new annotsv update and new annotations data to go with it. did work on fluse:
annotsv_data_dir: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/annotsv_data/annotsv_353/AnnotSV" # this needs to be created by annotsv itself, the installation independent from conda: use the official installation instructions here: https://github.com/lgmgeo/AnnotSV/blob/master/share/doc/AnnotSV/quickstart.md  
barcodes_lima_fasta: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/input/pacbio_barcodes.fasta"
sif_image_deepvariant: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/deepvariant_1.9.0.sif" # get this by doing: singularity pull docker://google/deepvariant:latest
bcftools_min_q_filter: "20" # only used if bcftools is used instead of deepvariant.
repeats_file: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/repeat_catalog_v1.hg38.1_to_1000bp_motifs.TRGT.bed"
deepvariant_checkpoint_dir: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/deepvariant_pacbio_190_model"
kraken2_db_folder: "/gpfs/project/databases/Kraken2-2022-09-28/kraken_db_plus"
snp_annotation_file: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/small_variants/00-All.vcf"  # Path to SNP annotation file wget ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf.gz 
sv_annotation_file: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/ALL.wgs.mergedSV.v8.20130502.svs.genotypes.GRCh38.vcf"    # Path to SV annotation file, should be gnomad_svs.vcf in best case ALL.wgs.mergedSV.v8.20130502.svs.genotypes.GRCh38.vcf.gz
vep_cache_dir: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/vep_hg38"
merge: true        # Set to true to enable merging of input files

# /gpfs/project/projects/bmfz_gtl/software/pb_variants/data/annotsv_data/annotsv_353/
# AnnotSV -SVinputFile test1.bed -outputFile ./test.annotated.tsv -svtBEDcol 4 -annotationsDir ../../../../share/AnnotSV
# AnnotSV 3.5 
