reference: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/inputs/reference.fasta"
output_dir: "results2" # no / at the end here allowed!! do path/to/dir instead of path/to/dir/
demultiplex: False  # Set to true to enable demultiplexing
merge: true        # Set to true to enable merging of input files
use_deepvariant: True # default = False, uses bcftools instead. deepvariant only works on the HPC for now
use_kraken2: True
use_cpg_tools: True
use_mitosaw: True # Mitochondrial variations, only hg38 supported
kraken2_db_folder: "/gpfs/project/databases/Kraken2-2022-09-28/kraken_db_plus"
snp_annotation_file: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/small_variants/00-All.vcf"  # Path to SNP annotation file wget ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf.gz 
sv_annotation_file: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/ALL.wgs.mergedSV.v8.20130502.svs.genotypes.GRCh38.vcf"    # Path to SV annotation file, should be gnomad_svs.vcf in best case ALL.wgs.mergedSV.v8.20130502.svs.genotypes.GRCh38.vcf.gz
use_sv_annotation: True # only hg38 for now, needs database file and annotsv data installed
use_snp_annotation: True 
use_deepvariant_hpc: True
annotsv_data_dir: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/annotsv_data/AnnotSV/share/AnnotSV" # this needs to be created by annotsv itself, the installation independent from conda: use the official installation instructions here: https://github.com/lgmgeo/AnnotSV/blob/master/share/doc/AnnotSV/quickstart.md  
barcodes_lima_fasta: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/input/pacbio_barcodes.fasta"
sif_image_deepvariant: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/deepvariant_1.9.0.sif" # get this by doing: singularity pull docker://google/deepvariant:latest
bcftools_min_q_filter: "20"
repeats_file: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/repeat_catalog_v1.hg38.1_to_1000bp_motifs.TRGT.bed"
deepvariant_checkpoint_dir: "/gpfs/project/projects/bmfz_gtl/software/pb_variants/data/deepvariant_pacbio_190_model"